### PR TITLE
Update regex to support /u/ share links

### PR DESCRIPTION
**Pull request by JeffreyCA**

### CODE REVIEW

**Comment by ichitaso** [comment]
Thank you

**Comment by WillGunn** [comment]
Something in this release broke official support for iphone se 2020:
image
@ichitaso

**Comment by ichitaso** [comment]
@WillGunn 
I rebuilt the IPA. Please confirm.  
[Apollo_1.15.11_ApolloPatcher_0.0.7.ipa](https://github.com/ichitaso/ApolloPatcher/releases/download/v0.0.7/Apollo_1.15.11_ApolloPatcher_0.0.7.ipa)

**Comment by WillGunn** [comment]
@ichitaso that looks to have worked.  What went wrong with the original build?

**Pull request merged**
