### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cyphs**
Add note about the original Bundle Identifier causing the app to stop working.

### CODE REVIEW

**Comment by simonk83** [comment]
How do we change that again, been a while since I installed this…

**Comment by Cyphs** [comment]
> How do we change that again, been a while since I installed this…

For simplicity, you can use the IPA provided by [Balackburn](https://github.com/Balackburn/Apollo/releases/latest) which already has the Bundle Identifier changed to something else and should just work as long as Reddit doesn’t also blacklist it or start using a whitelist.

Otherwise, you can change it yourself during install depending on what you are using (ESign, Sideloadly, etc.) or manually modify and repackage the Info.plist within the IPA if you know how.

**Comment by simonk83** [comment]
Ah yep, for anyone using Sideloadly you can just click Advanced Options, uncheck the "Use automatic bundle ID" and put in whatever. Thanks Cyphs

**Comment by Smelly-Ghost** [comment]
If there was issues on this repository I’d put it there but @ichitaso this IPA is not broken it seems. I have sent money via ko-fi I hope this can be addressed by your modified IPA. I’ll switch to @balackburn for now. Also cannot download recently uploaded videos anymore on your modified version. I’m happy to send more money your way if these can be fixed.

**Comment by SensehacK** [comment]
Thanks for the updated readme. Was confused to not work.

Do we have any official thread discussing why reddit added this to the ~~blacklist~~/blocklist now?

**Comment by Cyphs** [comment]
> Thanks for the updated readme. Was confused to not work.
> 
> Do we have any official thread discussing why reddit added this to the ~blacklist~/blocklist now?

There was news earlier about Reddit trying to stop other search engines besides Google (for now) from indexing its content in results, prevent scraping from LLMs (AI), and stop bots. This might be part of that somehow. 

Anyway, other users have now pointed out that it’s not necessarily the BundleID they are looking at, but the User Agent which is normally grabbed from the BundleID. The author of [Apollo-ImprovedCustomApi](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi) has implemented a fix in his tweak that will feed it a generic web User Agent making it work again, mentioned [here](https://github.com/JeffreyCA/Apollo-ImprovedCustomApi/issues/29#issuecomment-2251583467). Changing the BundleID is no longer necessary with that tweak.

@ichitaso can also implement this or do something similar into the provided IPA.

**Comment by ichitaso** [comment]
Fixed in [v0.0.9](https://github.com/ichitaso/ApolloPatcher/releases/tag/v0.0.9), thanks!

**Pull request closed without merging**
